-- ============================================
-- Store Locator Table (স্টোর লোকেটর)
-- ============================================
CREATE TABLE IF NOT EXISTS store_locator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    header_title TEXT NOT NULL,
    header_subtitle TEXT,
    header_image TEXT,
    section_title TEXT,
    section_subtitle TEXT,
    section_image TEXT,
    section_description TEXT,
    cta_text TEXT,
    cta_link TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- RLS সক্রিয় করা
-- ============================================
ALTER TABLE store_locator ENABLE ROW LEVEL SECURITY;

-- ============================================
-- পাবলিক রিড পলিসি
-- ============================================
CREATE POLICY "Public Select Store Locator" ON store_locator 
    FOR SELECT TO anon, authenticated 
    USING (is_active = true);

-- ============================================
-- অ্যাডমিন SELECT পলিসি
-- ============================================
CREATE POLICY "Admin select store locator" ON store_locator 
    FOR SELECT TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin'));

-- ============================================
-- অ্যাডমিন INSERT পলিসি
-- ============================================
CREATE POLICY "Admin insert store locator" ON store_locator 
    FOR INSERT TO authenticated 
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin'));

-- ============================================
-- অ্যাডমিন UPDATE পলিসি
-- ============================================
CREATE POLICY "Admin update store locator" ON store_locator 
    FOR UPDATE TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin')) 
    WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin'));

-- ============================================
-- অ্যাডমিন DELETE পলিসি
-- ============================================
CREATE POLICY "Admin delete store locator" ON store_locator 
    FOR DELETE TO authenticated 
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') IN ('admin', 'super_admin'));

-- ============================================
-- updated_at অটো-আপডেট ট্রিগার
-- ============================================
CREATE OR REPLACE FUNCTION update_store_locator_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS before_store_locator_update_timestamp ON store_locator;
CREATE TRIGGER before_store_locator_update_timestamp
    BEFORE UPDATE ON store_locator
    FOR EACH ROW
    EXECUTE FUNCTION update_store_locator_timestamp();

-- ============================================
-- ইনডেক্স
-- ============================================
CREATE INDEX IF NOT EXISTS idx_store_locator_active ON store_locator(is_active);
CREATE INDEX IF NOT EXISTS idx_store_locator_sort ON store_locator(sort_order);
